'use client'

import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { FormEvent, useState } from 'react'
import { ArrowRight, Check, Eye, EyeOff, Sparkles } from 'lucide-react'
import { createClient } from '@/lib/supabase/client'

export function AuthForm({ mode }: { mode: 'login' | 'register' }) {
  const router = useRouter(); const params = useSearchParams(); const isRegister = mode === 'register'
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [show, setShow] = useState(false); const [remember, setRemember] = useState(true); const [terms, setTerms] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  const submit = async (event: FormEvent) => { event.preventDefault(); setError(''); setMessage(''); if (!email.includes('@')) return setError('Enter a valid email address.'); if (password.length < 8) return setError('Password must be at least 8 characters.'); if (isRegister && !terms) return setError('Please accept the terms to continue.'); setLoading(true); try { const supabase = createClient(); const result = isRegister ? await supabase.auth.signUp({ email: email.trim(), password, options: { data: { full_name: name.trim() }, emailRedirectTo: process.env.NEXT_PUBLIC_DEV_SUPABASE_REDIRECT_URL ?? `${window.location.origin}/auth/callback` } }) : await supabase.auth.signInWithPassword({ email: email.trim(), password }); if (result.error) { const details = result.error.message.toLowerCase(); setError(details.includes('confirm') ? 'Check your email to confirm your account.' : details.includes('rate') ? 'Too many attempts. Please try again shortly.' : 'Unable to complete that request. Check your details and try again.'); return } if (isRegister) setMessage('Check your email to confirm your account.'); else router.replace('/') } catch { setError('We could not connect to the authentication service. Please try again.'); } finally { setLoading(false) } }
  return <main className="auth-page"><div className="auth-brand"><div className="brand-mark"><Sparkles size={18}/></div><span>HabitFlow</span></div><section className="auth-card"><div className="auth-intro"><p className="eyebrow">HABITFLOW / {isRegister ? 'WELCOME' : 'PRIVATE WORKSPACE'}</p><h1>{isRegister ? 'Build your better rhythm.' : 'Welcome back, Alex.'}</h1><p>{isRegister ? 'Create an account and make consistency feel natural.' : 'Pick up where your momentum left off.'}</p></div><form onSubmit={submit} className="auth-form">{isRegister && <label>Full name<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Alex Morgan" autoComplete="name" /></label>}<label>Email address<input value={email} onChange={(e) => setEmail(e.target.value)} placeholder="you@example.com" type="email" autoComplete="email" /></label><label>Password<div className="password-field"><input value={password} onChange={(e) => setPassword(e.target.value)} placeholder="At least 8 characters" type={show ? 'text' : 'password'} autoComplete={isRegister ? 'new-password' : 'current-password'} /><button type="button" onClick={() => setShow(!show)} aria-label={show ? 'Hide password' : 'Show password'}>{show ? <EyeOff size={16}/> : <Eye size={16}/>}</button></div></label>{!isRegister && <div className="auth-options"><label className="check-line"><input type="checkbox" checked={remember} onChange={(e) => setRemember(e.target.checked)}/> Remember me</label><button type="button" className="text-button">Forgot password?</button></div>}{isRegister && <label className="check-line"><input type="checkbox" checked={terms} onChange={(e) => setTerms(e.target.checked)}/><span>I agree to the terms and privacy policy.</span></label>}{error && <p className="auth-error">{error}</p>}{message && <p className="auth-success"><Check size={14}/>{message}</p>}<button className="primary auth-submit" disabled={loading}>{loading ? 'Working...' : isRegister ? 'Create account' : 'Sign in'}<ArrowRight size={15}/></button></form><p className="auth-switch">{isRegister ? 'Already have an account?' : 'New to HabitFlow?'} <Link href={isRegister ? '/login' : '/register'}>{isRegister ? 'Sign in' : 'Create an account'}</Link></p></section><p className="auth-footer">Your habits are yours. Always.</p></main>
}
